"""
Django settings for devlearn project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargamos variables de entorno desde .env (como emails y config sensible) 🔐
load_dotenv(BASE_DIR/'.env')
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2$4=h(5(=7larv%x%d@shgh25h$(cdz=&_%fr__^sm7r7h!8dd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

# Aquí registramos nuestras apps para que Django las reconozca 🧩
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.dashboard',   # Dashboard principal del usuario 🏠
    'apps.courses',     # Lógica de cursos, módulos y contenidos 📚
    'apps.profiles',    # Perfiles de usuario, instructor y student 🧑‍🎓
    'apps.support',     # Sistema de soporte/contacto por correo 📧
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'devlearn.urls'

# Config de plantillas (templates) 🎨
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ 
            BASE_DIR / 'templates'  # Carpeta global de templates 📁
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Context processor personalizado: mete la foto de perfil en TODAS las vistas 🖼️
                # Viene de apps/profiles/context_processors.py
                'apps.profiles.context_processors.profile_picture',
            ],
        },
    },
]

WSGI_APPLICATION = 'devlearn.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Base de datos SQLite (local, archivo db.sqlite3) 🗄️
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# Validadores de contraseña (seguridad básica de Django) 🔒
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-mx'  # Idioma: Español (México) 🌎

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static'  # Carpeta global de archivos estáticos 🎨
]

# Le decimos a Django que use nuestro modelo de usuario personalizado en vez del predeterminado 👤
# Sin esto, Django no sabrá qué modelo usar para las migraciones
# El modelo lo definimos en apps/profiles/models/user.py
AUTH_USER_MODEL = 'profiles.User'

# URLs de autenticación 🔑
LOGIN_URL = '/login/'                           # Si no has iniciado sesión, te manda aquí
LOGIN_REDIRECT_URL = 'student:course_list'      # Después de login vas al listado de cursos
LOGOUT_REDIRECT_URL = 'login'                   # Después de logout vuelves al login

# Archivos subidos por usuarios (imágenes de perfil, etc.) 🖼️
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Configuración de Correo para Soporte 📧
# Todas estas variables se pueden sobreescribir en el archivo .env
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '465'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'true').lower() == 'true'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'true').lower() == 'true' 
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@devlearn.com')
SUPPORT_INBOX = os.getenv('SUPPORT_INBOX', 'soporte@devlearn.com')  # Bandeja de soporte 📥
EMAIL_TIMEOUT = 20
