# Generated by Django 6.0.3 on 2026-05-05 21:09

import apps.courses.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_content_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='order',
            field=apps.courses.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
